name: Build Minecraft Native Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      jar_url:
        description: 'Minecraft Server Jar Download Link'
        required: true
        default: https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar
  
jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4
      
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 'latest-ea'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        run: |
          mkdir build-tmp
          mkdir native-tmp
          cd build-tmp
          curl -s -L "https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar" -o server.jar
          jar -xf server.jar
        
      - name: Build Fat Jar
        run: gradle shadowJar --no-daemon --parallel
        
      - name: Build Native Image
        run: |
            cd native-tmp
            native-image -jar ../build/libs/server-fat.jar -o native-server --initialize-at-run-time=io.netty --enable-monitoring=all --enable-https --enable-http --future-defaults=all --enable-preview -march=skylake -Os --static-nolibc --enable-native-access ALL-UNNAMED -esa -J-XX:-ExitOnOutOfMemoryError -J-Xmx30g -H:+UnlockExperimentalVMOptions -H:-ForeignAPISupport -H:DeadlockWatchdogInterval=0 -H:Preserve=module=ALL-UNNAMED
            
      - uses: actions/upload-artifact@v6
        with:
          path: native-tmp/*
