name: Build Minecraft Native Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      jar_url:
        description: 'Minecraft Server Jar Download Link'
        required: true
        default: https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar
  
jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4
      
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        run: |
          mkdir build-tmp
          cd build-tmp
          curl -s -L "https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar" -o server.jar
          jar -xf server.jar
        
      - name: Build Fat Jar
        run: gradle shadowJar --no-daemon --parallel
        
      - name: Build Native Image
        run: |
            mkdir native-tmp
            cd native-tmp
            native-image -jar ../build/libs/server-fat.jar -Dio.netty.noUnsafe=false --no-fallback --initialize-at-run-time=io.netty,joptsimple --enable-native-access ALL-UNNAMED --future-defaults=all -J-XX:-ExitOnOutOfMemoryError -H:Preserve=module=ALL-UNNAMED --enable-preview -esa --static-nolibc --enable-https --enable-http -march=skylake -J-Xmx16g -Os --enable-monitoring=all -o native-server
        
      - uses: actions/upload-artifact@v6
        with:
          path: native-tmp/*
