name: Build Minecraft Fat-Jar (GradleUp Shadow)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      jar_url:
        description: 'Minecraft Server Jar 下载链接'
        required: true
        default: 'https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # 2. 下载并解压元数据
      - name: Extract Metadata
        run: |
          mkdir -p build_temp
          cd build_temp
          wget "https://piston-data.mojang.com/v1/objects/3ca78d5068bf9b422f694d3f0820e289581c0f0d/server.jar"
          java -jar server.jar --nogui
          rm -f server.jar
          MAIN_CLASS=net.minecraft.server.Main
          echo "MAIN_CLASS=$MAIN_CLASS" >> $GITHUB_ENV

      # 3. 使用 com.gradleup.shadow 构建
      - name: Generate Build Script
        run: |
          cat <<EOF > build.gradle
            plugins {
                id 'java'
                id 'com.github.johnrengelman.shadow' version '4.0.0'
                id "io.paulbaker.shaded-log4j2-cachefile-transformer" version "0.9.4.4"
            }
            
            repositories {
                gradlePluginPortal()
                mavenCentral()
            }
            
            dependencies {
            	implementation fileTree(dir: 'build_temp', include: ['**/*.jar'])
            }
            
            shadowJar {
                duplicatesStrategy = 'fail'
                mergeServiceFiles()
                archiveFileName = 'server-fat.jar'
                manifest {
                    attributes 'Main-Class': '${{ env.MAIN_CLASS }}'
                }
                exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'，'**/Log4j2Plugins.dat'
            }
          EOF
        
      - name: Build Fat Jar
        run: gradle shadowJar --no-daemon --warning-mode all

      # 4. 提供结果下载
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-Fat-Jar.zip
          path: build/libs/server-fat.jar
